args: Namespace(config='experiments/human36m/train/human36m_alg.yaml', eval=False, eval_dataset='val', local_rank=None, logdir='./logs', seed=42)
Number of available GPUs: 4
Loading pretrained weights from: ./data/pretrained/human36m/pose_resnet_4.5_pixels_human36m.pth
Reiniting final layer filters: module.final_layer.weight
Reiniting final layer biases: module.final_layer.bias
Successfully loaded pretrained weights for backbone
Loading data...
Experiment name: human36m_alg_AlgebraicTriangulationNet@28.12.2021-18:21:13
3750 iters done.
7500 iters done.
11250 iters done.
15000 iters done.
18750 iters done.
22500 iters done.
26250 iters done.
30000 iters done.
33750 iters done.
37500 iters done.
41250 iters done.
45000 iters done.
48750 iters done.
52500 iters done.
56250 iters done.
60000 iters done.
63750 iters done.
67500 iters done.
71250 iters done.
75000 iters done.
78750 iters done.
82500 iters done.
86250 iters done.
90000 iters done.
93750 iters done.
97500 iters done.
101250 iters done.
105000 iters done.
108750 iters done.
112500 iters done.
116250 iters done.
120000 iters done.
123750 iters done.
127500 iters done.
131250 iters done.
135000 iters done.
138750 iters done.
142500 iters done.
146250 iters done.
150000 iters done.
153750 iters done.
157500 iters done.
161250 iters done.
165000 iters done.
168750 iters done.
172500 iters done.
176250 iters done.
180000 iters done.
183750 iters done.
187500 iters done.
191250 iters done.
195000 iters done.
198750 iters done.
202500 iters done.
206250 iters done.
210000 iters done.
213750 iters done.
217500 iters done.
221250 iters done.
225000 iters done.
228750 iters done.
232500 iters done.
236250 iters done.
args: Namespace(config='experiments/human36m/train/human36m_alg_no_damaged.yaml', eval=False, eval_dataset='val', local_rank=None, logdir='./logs', seed=42)
Number of available GPUs: 4
Loading pretrained weights from: ./data/pretrained/human36m/pose_resnet_4.5_pixels_human36m.pth
Reiniting final layer filters: module.final_layer.weight
Reiniting final layer biases: module.final_layer.bias
Successfully loaded pretrained weights for backbone
Loading data...
Experiment name: human36m_alg_AlgebraicTriangulationNet@29.12.2021-18:54:01
args: Namespace(config='experiments/human36m/train/human36m_vol_softmax.yaml', eval=False, eval_dataset='val', local_rank=None, logdir='./logs', seed=42)
Number of available GPUs: 4
Loading pretrained weights from: ./data/pretrained/human36m/pose_resnet_4.5_pixels_human36m.pth
Reiniting final layer filters: module.final_layer.weight
Reiniting final layer biases: module.final_layer.bias
Successfully loaded pretrained weights for backbone
Loading data...
Experiment name: human36m_vol_softmax_VolumetricTriangulationNet@29.12.2021-18:59:14
/home/kien/.local/lib/python3.6/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "train.py", line 484, in <module>
    main(args)
  File "train.py", line 463, in main
    n_iters_total_train = one_epoch(model, criterion, opt, config, train_dataloader, device, epoch, n_iters_total=n_iters_total_train, is_train=True, master=master, experiment_dir=experiment_dir, writer=writer)
  File "train.py", line 190, in one_epoch
    keypoints_3d_pred, heatmaps_pred, volumes_pred, confidences_pred, cuboids_pred, coord_volumes_pred, base_points_pred = model(images_batch, proj_matricies_batch, batch)
  File "/home/kien/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kien/learnable-triangulation-pytorch/mvn/models/triangulation.py", line 352, in forward
    volumes = self.volume_net(volumes)
  File "/home/kien/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kien/learnable-triangulation-pytorch/mvn/models/v2v.py", line 167, in forward
    x = self.back_layers(x)
  File "/home/kien/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kien/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/kien/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kien/learnable-triangulation-pytorch/mvn/models/v2v.py", line 42, in forward
    return F.relu(res + skip, True)
RuntimeError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 2; 10.76 GiB total capacity; 9.44 GiB already allocated; 102.94 MiB free; 9.49 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
args: Namespace(config='experiments/human36m/train/human36m_vol_softmax_no_damaged.yaml', eval=False, eval_dataset='val', local_rank=None, logdir='./logs', seed=42)
Number of available GPUs: 4
Loading pretrained weights from: ./data/pretrained/human36m/pose_resnet_4.5_pixels_human36m.pth
Reiniting final layer filters: module.final_layer.weight
Reiniting final layer biases: module.final_layer.bias
Successfully loaded pretrained weights for backbone
Loading data...
Traceback (most recent call last):
  File "train.py", line 484, in <module>
    main(args)
  File "train.py", line 443, in main
    train_dataloader, val_dataloader, train_sampler = setup_dataloaders(config, distributed_train=is_distributed)
  File "train.py", line 116, in setup_dataloaders
    train_dataloader, val_dataloader, train_sampler = setup_human36m_dataloaders(config, is_train, distributed_train)
  File "train.py", line 96, in setup_human36m_dataloaders
    crop=config.dataset.val.crop if hasattr(config.dataset.val, "crop") else True,
  File "/home/kien/learnable-triangulation-pytorch/mvn/datasets/human36m.py", line 111, in __init__
    f"has {len(self.keypoints_3d_pred)}. Did you follow all preprocessing instructions carefully?"
AssertionError: [train=False, test=True] ./data/human36m/extra/human36m-multiview-labels-GTbboxes.npy has 2107 samples, but './data/pretrained/human36m/results/val.pkl' has 2181. Did you follow all preprocessing instructions carefully?
240000 iters done.
3750 iters done.
243750 iters done.
7500 iters done.
247500 iters done.
11250 iters done.
251250 iters done.
15000 iters done.
255000 iters done.
18750 iters done.
258750 iters done.
22500 iters done.
262500 iters done.
26250 iters done.
266250 iters done.
30000 iters done.
270000 iters done.
33750 iters done.
273750 iters done.
37500 iters done.
277500 iters done.
41250 iters done.
281250 iters done.
45000 iters done.
285000 iters done.
48750 iters done.
288750 iters done.
52500 iters done.
292500 iters done.
56250 iters done.
296250 iters done.
60000 iters done.
300000 iters done.
63750 iters done.
303750 iters done.
67500 iters done.
307500 iters done.
71250 iters done.
311250 iters done.
75000 iters done.
315000 iters done.
78750 iters done.
318750 iters done.
82500 iters done.
322500 iters done.
86250 iters done.
326250 iters done.
90000 iters done.
330000 iters done.
93750 iters done.
333750 iters done.
97500 iters done.
337500 iters done.
101250 iters done.
341250 iters done.
105000 iters done.
345000 iters done.
108750 iters done.
348750 iters done.
112500 iters done.
352500 iters done.
116250 iters done.
356250 iters done.
120000 iters done.
360000 iters done.
363750 iters done.
123750 iters done.
367500 iters done.
127500 iters done.
371250 iters done.
131250 iters done.
375000 iters done.
135000 iters done.
378750 iters done.
138750 iters done.
382500 iters done.
142500 iters done.
146250 iters done.
150000 iters done.
153750 iters done.
157500 iters done.
161250 iters done.
165000 iters done.
168750 iters done.
172500 iters done.
args: Namespace(config='experiments/roofing/train/roofing_alg.yaml', eval=False, eval_dataset='val', local_rank=None, logdir='./logs', seed=42)
Number of available GPUs: 4
Loading pretrained weights from: ./data/pretrained/human36m/pose_resnet_4.5_pixels_human36m.pth
Reiniting final layer filters: module.final_layer.weight
Reiniting final layer biases: module.final_layer.bias
Successfully loaded pretrained weights for backbone
Loading data...
Experiment name: roofing_alg_AlgebraicTriangulationNet@30.12.2021-14:00:31
176250 iters done.
3750 iters done.
180000 iters done.
7500 iters done.
183750 iters done.
11250 iters done.
187500 iters done.
15000 iters done.
args: Namespace(config='experiments/roofing/train/roofing_alg.yaml', eval=False, eval_dataset='val', local_rank=None, logdir='./logs', seed=42)
Number of available GPUs: 4
Loading pretrained weights from: ./data/pretrained/human36m/pose_resnet_4.5_pixels_human36m.pth
Reiniting final layer filters: module.final_layer.weight
Reiniting final layer biases: module.final_layer.bias
Successfully loaded pretrained weights for backbone
Loading data...
Experiment name: roofing_alg_AlgebraicTriangulationNet@30.12.2021-15:41:36
191250 iters done.
18750 iters done.
195000 iters done.
3750 iters done.
22500 iters done.
198750 iters done.
26250 iters done.
202500 iters done.
7500 iters done.
30000 iters done.
206250 iters done.
33750 iters done.
210000 iters done.
11250 iters done.
37500 iters done.
213750 iters done.
41250 iters done.
15000 iters done.
217500 iters done.
45000 iters done.
221250 iters done.
48750 iters done.
18750 iters done.
225000 iters done.
52500 iters done.
228750 iters done.
22500 iters done.
56250 iters done.
232500 iters done.
60000 iters done.
26250 iters done.
236250 iters done.
63750 iters done.
240000 iters done.
67500 iters done.
30000 iters done.
243750 iters done.
71250 iters done.
247500 iters done.
75000 iters done.
33750 iters done.
251250 iters done.
78750 iters done.
82500 iters done.
37500 iters done.
86250 iters done.
41250 iters done.
90000 iters done.
93750 iters done.
45000 iters done.
97500 iters done.
101250 iters done.
48750 iters done.
105000 iters done.
108750 iters done.
52500 iters done.
112500 iters done.
116250 iters done.
56250 iters done.
120000 iters done.
60000 iters done.
123750 iters done.
127500 iters done.
63750 iters done.
131250 iters done.
135000 iters done.
67500 iters done.
138750 iters done.
71250 iters done.
75000 iters done.
78750 iters done.
82500 iters done.
86250 iters done.
90000 iters done.
93750 iters done.
97500 iters done.
101250 iters done.
105000 iters done.
108750 iters done.
112500 iters done.
116250 iters done.
120000 iters done.
123750 iters done.
127500 iters done.
131250 iters done.
135000 iters done.
138750 iters done.
142500 iters done.
usage: train.py [-h] --config CONFIG [--eval] [--eval_dataset EVAL_DATASET]
                [--local_rank LOCAL_RANK] [--seed SEED] [--logdir LOGDIR]
train.py: error: unrecognized arguments: --logs ./logs
args: Namespace(config='experiments/human36m/train/human36m_vol_softmax_no_damaged.yaml', eval=False, eval_dataset='val', local_rank=None, logdir='./logs', seed=42)
Number of available GPUs: 4
Loading pretrained weights from: ./data/pretrained/human36m/pose_resnet_4.5_pixels_human36m.pth
Reiniting final layer filters: module.final_layer.weight
Reiniting final layer biases: module.final_layer.bias
Successfully loaded pretrained weights for backbone
Loading data...
Experiment name: human36m_vol_softmax_VolumetricTriangulationNet@31.12.2021-18:21:26
/home/kien/.local/lib/python3.6/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "train.py", line 487, in <module>
    main(args)
  File "train.py", line 466, in main
    n_iters_total_train = one_epoch(model, criterion, opt, config, train_dataloader, device, epoch, n_iters_total=n_iters_total_train, is_train=True, master=master, experiment_dir=experiment_dir, writer=writer)
  File "train.py", line 190, in one_epoch
    keypoints_3d_pred, heatmaps_pred, volumes_pred, confidences_pred, cuboids_pred, coord_volumes_pred, base_points_pred = model(images_batch, proj_matricies_batch, batch)
  File "/home/kien/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kien/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 169, in forward
    return self.gather(outputs, self.output_device)
  File "/home/kien/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 181, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/home/kien/.local/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 78, in gather
    res = gather_map(outputs)
  File "/home/kien/.local/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 73, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/home/kien/.local/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 73, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/home/kien/.local/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 73, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
TypeError: zip argument #1 must support iteration
args: Namespace(config='experiments/human36m/train/human36m_alg_no_damaged.yaml', eval=False, eval_dataset='val', local_rank=None, logdir='./logs', seed=42)
Number of available GPUs: 4
Loading pretrained weights from: ./data/pretrained/human36m/pose_resnet_4.5_pixels_human36m.pth
Reiniting final layer filters: module.final_layer.weight
Reiniting final layer biases: module.final_layer.bias
Successfully loaded pretrained weights for backbone
Loading data...
Experiment name: human36m_alg_AlgebraicTriangulationNet@31.12.2021-19:48:21
3750 iters done.
7500 iters done.
11250 iters done.
15000 iters done.
18750 iters done.
22500 iters done.
26250 iters done.
30000 iters done.
33750 iters done.
37500 iters done.
41250 iters done.
45000 iters done.
48750 iters done.
Error:  svd_cuda: (Batch element 0): The algorithm failed to converge because the input matrix is ill-conditioned or has too many repeated singular values (error code: 5).
Traceback (most recent call last):
  File "train.py", line 487, in <module>
    main(args)
  File "train.py", line 466, in main
    n_iters_total_train = one_epoch(model, criterion, opt, config, train_dataloader, device, epoch, n_iters_total=n_iters_total_train, is_train=True, master=master, experiment_dir=experiment_dir, writer=writer)
  File "train.py", line 188, in one_epoch
    keypoints_3d_pred, keypoints_2d_pred, heatmaps_pred, confidences_pred = model(images_batch, proj_matricies_batch, batch)
  File "/home/kien/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kien/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/kien/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/kien/.local/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/kien/.local/lib/python3.6/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
NameError: Caught NameError in replica 2 on device 2.
Original Traceback (most recent call last):
  File "/home/kien/learnable-triangulation-pytorch/mvn/models/triangulation.py", line 190, in forward
    confidences_batch=alg_confidences
  File "/home/kien/learnable-triangulation-pytorch/mvn/utils/multiview.py", line 180, in triangulate_batch_of_points
    point_3d = triangulate_point_from_multiple_views_linear_torch(proj_matricies_batch[batch_i], points, confidences=confidences)
  File "/home/kien/learnable-triangulation-pytorch/mvn/utils/multiview.py", line 163, in triangulate_point_from_multiple_views_linear_torch
    u, s, vh = torch.svd(A.view(-1, 4))
RuntimeError: svd_cuda: (Batch element 0): The algorithm failed to converge because the input matrix is ill-conditioned or has too many repeated singular values (error code: 5).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kien/.local/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/kien/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kien/learnable-triangulation-pytorch/mvn/models/triangulation.py", line 195, in forward
    print("confidences =", confidences_batch_pred)
NameError: name 'confidences_batch_pred' is not defined

args: Namespace(config='experiments/human36m/train/human36m_alg_no_damaged.yaml', eval=False, eval_dataset='val', local_rank=None, logdir='./logs', seed=42)
Number of available GPUs: 4
Loading pretrained weights from: ./data/pretrained/human36m/pose_resnet_4.5_pixels_human36m.pth
Reiniting final layer filters: module.final_layer.weight
Reiniting final layer biases: module.final_layer.bias
Successfully loaded pretrained weights for backbone
Loading data...
Experiment name: human36m_alg_AlgebraicTriangulationNet@01.01.2022-18:33:27
Traceback (most recent call last):
  File "train.py", line 487, in <module>
    main(args)
  File "train.py", line 466, in main
    n_iters_total_train = one_epoch(model, criterion, opt, config, train_dataloader, device, epoch, n_iters_total=n_iters_total_train, is_train=True, master=master, experiment_dir=experiment_dir, writer=writer)
  File "train.py", line 188, in one_epoch
    keypoints_3d_pred, keypoints_2d_pred, heatmaps_pred, confidences_pred = model(images_batch, proj_matricies_batch, batch)
  File "/home/kien/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kien/learnable-triangulation-pytorch/mvn/models/triangulation.py", line 158, in forward
    heatmaps, _, alg_confidences, _ = self.backbone(images)
  File "/home/kien/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kien/learnable-triangulation-pytorch/mvn/models/pose_resnet.py", line 312, in forward
    x = self.deconv_layers(x)
  File "/home/kien/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kien/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/kien/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kien/.local/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 179, in forward
    self.eps,
  File "/home/kien/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 2283, in batch_norm
    input, weight, bias, running_mean, running_var, training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 144.00 MiB (GPU 0; 10.76 GiB total capacity; 9.24 GiB already allocated; 28.94 MiB free; 9.51 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
args: Namespace(config='experiments/human36m/train/human36m_alg_no_damaged.yaml', eval=False, eval_dataset='val', local_rank=None, logdir='./logs', seed=42)
Number of available GPUs: 4
Loading pretrained weights from: ./data/pretrained/human36m/pose_resnet_4.5_pixels_human36m.pth
Reiniting final layer filters: module.final_layer.weight
Reiniting final layer biases: module.final_layer.bias
Successfully loaded pretrained weights for backbone
Loading data...
Experiment name: human36m_alg_AlgebraicTriangulationNet@01.01.2022-18:35:45
Traceback (most recent call last):
  File "train.py", line 487, in <module>
    main(args)
  File "train.py", line 466, in main
    n_iters_total_train = one_epoch(model, criterion, opt, config, train_dataloader, device, epoch, n_iters_total=n_iters_total_train, is_train=True, master=master, experiment_dir=experiment_dir, writer=writer)
  File "train.py", line 188, in one_epoch
    keypoints_3d_pred, keypoints_2d_pred, heatmaps_pred, confidences_pred = model(images_batch, proj_matricies_batch, batch)
  File "/home/kien/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kien/learnable-triangulation-pytorch/mvn/models/triangulation.py", line 158, in forward
    heatmaps, _, alg_confidences, _ = self.backbone(images)
  File "/home/kien/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kien/learnable-triangulation-pytorch/mvn/models/pose_resnet.py", line 312, in forward
    x = self.deconv_layers(x)
  File "/home/kien/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kien/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/kien/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kien/.local/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 179, in forward
    self.eps,
  File "/home/kien/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 2283, in batch_norm
    input, weight, bias, running_mean, running_var, training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 144.00 MiB (GPU 0; 10.76 GiB total capacity; 9.24 GiB already allocated; 28.94 MiB free; 9.51 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
args: Namespace(config='experiments/human36m/train/human36m_vol_softmax_no_damaged.yaml', eval=False, eval_dataset='val', local_rank=None, logdir='./logs', seed=42)
Number of available GPUs: 4
Loading pretrained weights from: ./data/pretrained/human36m/pose_resnet_4.5_pixels_human36m.pth
Reiniting final layer filters: module.final_layer.weight
Reiniting final layer biases: module.final_layer.bias
Successfully loaded pretrained weights for backbone
Loading data...
Experiment name: human36m_vol_softmax_VolumetricTriangulationNet@01.01.2022-18:37:23
/home/kien/.local/lib/python3.6/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "train.py", line 487, in <module>
    main(args)
  File "train.py", line 466, in main
    n_iters_total_train = one_epoch(model, criterion, opt, config, train_dataloader, device, epoch, n_iters_total=n_iters_total_train, is_train=True, master=master, experiment_dir=experiment_dir, writer=writer)
  File "train.py", line 190, in one_epoch
    keypoints_3d_pred, heatmaps_pred, volumes_pred, confidences_pred, cuboids_pred, coord_volumes_pred, base_points_pred = model(images_batch, proj_matricies_batch, batch)
  File "/home/kien/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kien/learnable-triangulation-pytorch/mvn/models/triangulation.py", line 352, in forward
    volumes = self.volume_net(volumes)
  File "/home/kien/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kien/learnable-triangulation-pytorch/mvn/models/v2v.py", line 167, in forward
    x = self.back_layers(x)
  File "/home/kien/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kien/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/kien/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kien/learnable-triangulation-pytorch/mvn/models/v2v.py", line 42, in forward
    return F.relu(res + skip, True)
RuntimeError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 10.76 GiB total capacity; 9.44 GiB already allocated; 102.94 MiB free; 9.49 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
